train:
  batch_size_per_gpu: 32
  data_min_axis_size: 48
  OFFICIAL_EPOCH_LENGTH: 125
student:
  full_pretrained_weights: ''  # copy the zorglub weights to lucia first
crops:
  global_crops_size: 112
  local_crops_size: 64
optim:
  base_lr: 0.001
evaluation:
  eval_period_iterations: 3125
